version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always