version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_cache:/var/cache/nginx
    ports:
      - "80:80"
    restart: always